---
name: Update README Table

on:
  push:
    paths:
      - "pkgs/**/default.nix"
      - "pkgs/**/.pr"
      - "README.md"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run script to update README
        run: python .github/scripts/update_readme_table.py

      - name: Commit and push if README changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs(README.md): Update package table in README"
            git push
          fi

